export const ProductItems=[
    {
    id:"1",
    Title:"Acer Aspire 5 Core i5 7th Gen A515-51G Laptop",
    Brand:"Acer",
    Price:"45990",
    Color:"silver",
    imageUrl:"https://rukminim1.flixcart.com/image/832/832/jmz7csw0/computer/h/e/f/acer-na-laptop-original-imaf9zyp7u9jjz8n.jpeg?q=70",
    processor:"Intel Core i5 Processor (7th Gen)",
    ram:"8 GB DDR4 RAM",
    os:"64 bit Windows 10 Operating System",
    hardDisk:"1 TB HDD",
    display:"39.62 cm (15.6 inch) Display",
    warrenty:"1 Year International Travelers Warranty (ITW)",
    rating:"",
    reviews:"",
    desc:"A phone that captures the world, just the way you see it - that’s how you will describe your tryst with the Samsung Galaxy A7 smartphone whose 8 MP 120-degree Ultra Wide Lens pave the way for gorgeous, unrestricted wide-angle pictures.",                   Avatar:"https://rukminim1.flixcart.com/image/832/832/jmgmmq80/mobile/r/z/z/samsung-galaxy-a7-sm-a750fzkhins-original-imaf9d35udmkv2rg.jpeg?q=70",
    Seller:"Capgemini Retailer",qty:1
  },
  {
    id:"2",
    Title:"Acer Predator Helios 300 Core i5 8th Gen ",
    Brand:"Acer",
    Price:"91990",
    Color:"silver",
    imageUrl:"https://rukminim1.flixcart.com/image/312/312/jmz7csw0/computer/a/u/3/lenovo-na-laptop-original-imaf9ry4btbxnv4k.jpeg?q=70",
    processor:"Intel Core i5 Processor (8th Gen)",
    ram:"8 GB DDR4 RAM",
    os:"64 bit Windows 10 Operating System",
    hardDisk:"1 TB HDD",
    display:"39.62 cm (15.6 inch) Display",
    warrenty:"1 Year International Travelers Warranty (ITW)",
    rating:"",
    reviews:"",
    desc:"A phone that captures the world, just the way you see it - that’s how you will describe your tryst with the Samsung Galaxy A7 smartphone whose 8 MP 120-degree Ultra Wide Lens pave the way for gorgeous, unrestricted wide-angle pictures.",                   Avatar:"https://rukminim1.flixcart.com/image/832/832/jmgmmq80/mobile/r/z/z/samsung-galaxy-a7-sm-a750fzkhins-original-imaf9d35udmkv2rg.jpeg?q=70",
    Seller:"Capgemini Retailer",qty:1
  }
  ,
  {
    id:"3",
    Title:"Dell Inspiron 15 3000 APU Dual Core A9 3565 Laptop",
    Brand:"Dell",
    Price:"28990",
    Color:"silver",
    imageUrl:"https://rukminim1.flixcart.com/image/312/312/jly1wnk0/computer/e/r/f/dell-na-original-imaf8ytczf3gwfrp.jpeg?q=70",
    processor:"AMD APU Dual Core A9 Processor",
    ram:"8 GB DDR4 RAM",
    os:"64 bit Windows 10 Operating System",
    hardDisk:"1 TB HDD",
    display:"39.62 cm (15.6 inch) Display",
    warrenty:"1 Year International Travelers Warranty (ITW)",
    rating:"",
    reviews:"",
    desc:"A phone that captures the world, just the way you see it - that’s how you will describe your tryst with the Samsung Galaxy A7 smartphone whose 8 MP 120-degree Ultra Wide Lens pave the way for gorgeous, unrestricted wide-angle pictures.",                   Avatar:"https://rukminim1.flixcart.com/image/832/832/jmgmmq80/mobile/r/z/z/samsung-galaxy-a7-sm-a750fzkhins-original-imaf9d35udmkv2rg.jpeg?q=70",
    Seller:"Capgemini Retailer",qty:1
  },
  {
    id:"4",
    Title:"HP 15 APU Dual Core A4  15-db0209au Laptop",
    Brand:"HP",
    Price:"22990",
    Color:"silver",
    imageUrl:"https://rukminim1.flixcart.com/image/312/312/jmz7csw0/computer/f/b/c/hp-na-laptop-original-imaf9zypu2mjhzmk.jpeg?q=70",
    processor:"AMD APU Dual Core A4 Processor",
    ram:"4 GB DDR4 RAM",
    os:"64 bit Windows 10 Operating System",
    hardDisk:"1 TB HDD",
    display:"39.62 cm (15.6 inch) Display",
    warrenty:"1 Year International Travelers Warranty (ITW)",
    rating:"",
    reviews:"",
    desc:"A phone that captures the world, just the way you see it - that’s how you will describe your tryst with the Samsung Galaxy A7 smartphone whose 8 MP 120-degree Ultra Wide Lens pave the way for gorgeous, unrestricted wide-angle pictures.",                   Avatar:"https://rukminim1.flixcart.com/image/832/832/jmgmmq80/mobile/r/z/z/samsung-galaxy-a7-sm-a750fzkhins-original-imaf9d35udmkv2rg.jpeg?q=70",
    Seller:"Capgemini Retailer",qty:1
  },
  {
    id:"5",
    Title:"Apple MacBook Air Core i5 5th Gen MQD32HN/A A1466",
    Brand:"Apple",
    Price:"79990",
    Color:"silver",
    imageUrl:"https://rukminim1.flixcart.com/image/312/312/jsnjbm80/computer/j/8/c/apple-na-thin-and-light-laptop-original-imafe6f78hur4jbh.jpeg?q=70",
    processor:"AMD APU Dual Core A4 Processor",
    ram:"8 GB DDR3 RAM",
    os:"64 bit Mac OS Operating System",
    hardDisk:"128 GB SSD",
    display:"33.78 cm (13.3 inch) Display",
    warrenty:"1 Year Carry In Warranty",
    rating:"",
    reviews:"",
    desc:"A phone that captures the world, just the way you see it - that’s how you will describe your tryst with the Samsung Galaxy A7 smartphone whose 8 MP 120-degree Ultra Wide Lens pave the way for gorgeous, unrestricted wide-angle pictures.",                   Avatar:"https://rukminim1.flixcart.com/image/832/832/jmgmmq80/mobile/r/z/z/samsung-galaxy-a7-sm-a750fzkhins-original-imaf9d35udmkv2rg.jpeg?q=70",
    Seller:"Capgemini Retailer",qty:1
  }

]